---
# NAS Storage Configuration Handlers

- name: Restart nfs server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted
    daemon_reload: true

- name: Restart samba
  ansible.builtin.systemd:
    name: smbd
    state: restarted
    daemon_reload: true

- name: Reload nfs exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Restart nmbd
  ansible.builtin.systemd:
    name: nmbd
    state: restarted
    daemon_reload: true
