---
# Proxmox Host Setup Handlers

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted
  notify: Restart proxmox services

- name: Restart proxmox services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - pveproxy
    - pvedaemon
    - pve-cluster
  failed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart zfs-zed
  ansible.builtin.systemd:
    name: zfs-zed
    state: restarted

- name: Restart zfs services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - zfs-import-cache
    - zfs-mount
    - zfs-import.target
  failed_when: false

- name: Restart node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted
