---
# Service Management - Network Configuration Tasks
# Configure networking for services

- name: Configure service network settings
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ service.vmid }}"
    net:
      net0: "virtio,bridge={{ service.network.bridge | default('vmbr0') }},firewall={{ service.network.firewall | default(1) }}"
    update: true
  when:
    - service.type == 'vm'
    - service.network is defined

- name: Configure container network settings
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ service.vmid }}"
    netif:
      net0: "name=eth0,bridge={{ service.network.bridge | default('vmbr0') }},ip={{ service.network.ip | default('dhcp') }},gw={{ service.network.gateway | default('') }}"
    update: true
  when:
    - service.type == 'container'
    - service.network is defined

- name: Configure firewall rules for service
  community.general.proxmox_firewall_rules:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ service.vmid }}"
    rules: "{{ service.firewall_rules | default([]) }}"
    state: present
  when: service.firewall_rules is defined

- name: Configure service DNS entries
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ service.vmid }}"
    searchdomain: "{{ service.network.search_domain | default('local') }}"
    nameservers: "{{ service.network.dns_servers | default(['8.8.8.8', '1.1.1.1']) | join(' ') }}"
    update: true
  when:
    - service.type == 'vm'
    - service.network is defined
    - service.network.dns_servers is defined or service.network.search_domain is defined
