---
# Expandable Service Management Role
# This role creates a reusable framework for managing services across different server types

- name: Include server-type specific service definitions
  ansible.builtin.include_vars: "services/{{ server_type }}.yml"
  when: server_type is defined

- name: Set default service configuration
  ansible.builtin.set_fact:
    available_services: "{{ available_services | default({}) | combine(default_services | default({})) }}"

# Universal service deployment framework
- name: Deploy configured services
  ansible.builtin.include_tasks: "deploy_service.yml"
  loop: "{{ available_services.keys() | list }}"
  loop_control:
    loop_var: service_name
  when: 
    - services[service_name] | default(false)
    - available_services[service_name] is defined

# Service-specific post-deployment tasks
- name: Configure service networking
  ansible.builtin.include_tasks: "configure_networking.yml"
  when: service_networking is defined

- name: Setup service monitoring
  ansible.builtin.include_tasks: "setup_monitoring.yml"
  when: monitoring.enabled | default(false)

- name: Configure service backups
  ansible.builtin.include_tasks: "setup_backups.yml"
  when: backup.enabled | default(false)
