---
# Proxmox NAS Service Definitions
# Define available services for proxmox-nas server type

default_services:
  truenas:
    type: vm
    vmid: 100
    cores: 4
    memory: 8192
    balloon: 2048
    disk_size: "100G"
    storage_passthrough: true
    ostype: other
    tags: "truenas,nas,storage"
    description: "TrueNAS NAS operating system"
    required_ports: [80, 443]
    validation:
      port: 80
      path: ""
      expected_status: 200

  proxmox_backup_server:
    type: vm
    vmid: 110
    cores: 4
    memory: 4096
    balloon: 1024
    os_disk_size: "32G"
    backup_disk_size: "500G"
    ostype: l26
    tags: "pbs,backup,storage"
    description: "Proxmox Backup Server"
    required_ports: [8007]
    validation:
      port: 8007
      path: ""
      expected_status: 200

  nextcloud:
    type: container
    vmid: 201
    cores: 2
    memory: 2048
    swap: 512
    disk_size: "20"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
    features: ["nesting=1", "mount=nfs;cifs"]
    tags: "nextcloud,web,storage"
    description: "Nextcloud cloud storage and collaboration"
    required_ports: [80, 443]
    data_mount:
      source: "/mnt/nas/nextcloud"
      target: "/var/lib/nextcloud/data"
    validation:
      port: 80
      path: "login"
      expected_status: 200

  coder:
    type: container
    vmid: 202
    cores: 2
    memory: 2048
    swap: 512
    disk_size: "20"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
    features: ["nesting=1", "docker=1"]
    tags: "coder,development,vscode"
    description: "Coder VS Code server for remote development"
    required_ports: [7080]
    validation:
      port: 7080
      path: ""
      expected_status: 200

  memos:
    type: container
    vmid: 203
    cores: 1
    memory: 512
    swap: 256
    disk_size: "8"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
    features: ["nesting=1"]
    tags: "memos,notes,web"
    description: "Memos note-taking and knowledge management"
    required_ports: [5230]
    validation:
      port: 5230
      path: ""
      expected_status: 200

  gitlab:
    type: vm
    vmid: 120
    cores: 4
    memory: 8192
    balloon: 2048
    disk_size: "100G"
    ostype: l26
    tags: "gitlab,git,ci"
    description: "GitLab DevOps platform"
    required_ports: [80, 443, 22]
    validation:
      port: 80
      path: ""
      expected_status: 302

  jellyfin:
    type: container
    vmid: 204
    cores: 2
    memory: 2048
    swap: 512
    disk_size: "16"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
    features: ["nesting=1"]
    tags: "jellyfin,media,streaming"
    description: "Jellyfin media server"
    required_ports: [8096]
    media_mount:
      source: "/mnt/nas/media"
      target: "/var/lib/jellyfin/media"
    validation:
      port: 8096
      path: ""
      expected_status: 200

  pihole:
    type: container
    vmid: 205
    cores: 1
    memory: 512
    swap: 256
    disk_size: "8"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
    features: ["nesting=1"]
    tags: "pihole,dns,adblock"
    description: "Pi-hole DNS ad blocker"
    required_ports: [53, 80]
    validation:
      port: 80
      path: "admin"
      expected_status: 200
