---
# Service Management Handlers

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: Reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    enabled: true

- name: Update service inventory
  ansible.builtin.lineinfile:
    path: "/etc/ansible/hosts"
    line: "{{ service.name }} ansible_host={{ service.network.ip | default('localhost') }}"
    create: true
    mode: '0644'

- name: Refresh proxmox cache
  ansible.builtin.meta: refresh_inventory
