name: Test
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: ./dev-setup.sh

      - name: Run Core Tests
        run: |
          ./tests/core/test_config.sh
          ./tests/core/test_logging.sh

      - name: Run Integration Tests
        run: ./tests/integration/test_deployment.sh

  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: ./dev-setup.sh

      - name: Validate Configuration
        run: ./validate-config.sh

      - name: Check Prerequisites
        run: ./scripts/core/init.sh
